version: "3.8"


services:
  abs-signaling-server:
    container_name: abs-signaling-server
    image: abs-signaling-server:latest
    build:
      context: ./
      dockerfile: ./Dockerfile

    ports:
      - "9999:9999"

    labels:
      - "traefik.enable=false"

    volumes:
      - type: volume
        source: abs_signaling_node_modules
        target: /server/node_modules

    restart: unless-stopped

  abs-mqtt-server:
    container_name: abs-mqtt-server
    image: eclipse-mosquitto

    ports:
      - "1883:1883"
      - "9091:9091"

    labels:
      - "traefik.enable=false"

    volumes:
      - type: bind
        source: ./mqtt_server/data/config
        target: /mosquitto/config
      - type: bind
        source: ./mqtt_server/data/data
        target: /mosquitto/data
      - type: bind
        source: ./mqtt_server/data/log
        target: /mosquitto/log

    restart: unless-stopped


volumes:
  abs_signaling_node_modules: